weather:
    pattern: /weather
    defaults: { _controller: SiteForecastBundle:Weather:index}

weather_ajax:
    pattern: /weather/ajax
    defaults: { _controller: SiteForecastBundle:Weather:getWeather}